# Generated by Django 3.0.4 on 2020-03-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_likes',
            new_name='users_like',
        ),
    ]
